// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/properties/base/anyProperty.v1.proto

package com.properties;

public interface AnyPropertyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:properties.AnyProperty)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.properties.MesaProperty mesa_property = 1 [json_name = "mesaProperty"];</code>
   * @return Whether the mesaProperty field is set.
   */
  boolean hasMesaProperty();
  /**
   * <code>.properties.MesaProperty mesa_property = 1 [json_name = "mesaProperty"];</code>
   * @return The mesaProperty.
   */
  MesaProperty getMesaProperty();
  /**
   * <code>.properties.MesaProperty mesa_property = 1 [json_name = "mesaProperty"];</code>
   */
  MesaPropertyOrBuilder getMesaPropertyOrBuilder();

  /**
   * <code>.properties.MetaProperty meta_property = 2 [json_name = "metaProperty"];</code>
   * @return Whether the metaProperty field is set.
   */
  boolean hasMetaProperty();
  /**
   * <code>.properties.MetaProperty meta_property = 2 [json_name = "metaProperty"];</code>
   * @return The metaProperty.
   */
  MetaProperty getMetaProperty();
  /**
   * <code>.properties.MetaProperty meta_property = 2 [json_name = "metaProperty"];</code>
   */
  MetaPropertyOrBuilder getMetaPropertyOrBuilder();

  AnyProperty.ImplCase getImplCase();
}
