// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/make/service.v1.proto

package orders.transactions.make;

public final class ServiceV1 {
  private ServiceV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:modules/orders/internal/transactions/m" +
      "ake/service.v1.proto\022\030orders.transaction" +
      "s.make\032\034google/api/annotations.proto\032:mo" +
      "dules/orders/internal/transactions/make/" +
      "message.v1.proto\032;modules/orders/interna" +
      "l/transactions/make/response.v1.proto2w\n" +
      "\007Service\022l\n\006Handle\022!.orders.transactions" +
      ".make.Message\032\".orders.transactions.make" +
      ".Response\"\033\202\323\344\223\002\025\"\023/mantle/orders/makeb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          orders.transactions.make.MessageV1.getDescriptor(),
          orders.transactions.make.ResponseV1.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    orders.transactions.make.MessageV1.getDescriptor();
    orders.transactions.make.ResponseV1.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
