package commonConstants

object Module {

  val COMMON_UTILITIES_MICRO_NUMBER = "UTILITIES_MICRO_NUMBER"
  val COMMON_UTILITIES_ATTO_NUMBER = "UTILITIES_ATTO_NUMBER"
  val COMMON_UTILITIES_BECH32 = "UTILITIES_BECH32"
  val COMMON_UTILITIES_DATE = "UTILITIES_DATE"
  val COMMON_UTILITIES_WALLET = "UTILITIES_WALLET"
  val COMMON_UTILITIES_SECRETS = "UTILITIES_SECRETS"

  val COMMON_UTILITIES_ID = "COMMON_UTILITIES_ID"

}
