package constants

object Module {

  val MICRO_NUMBER = "MICRO_NUMBER"
  val BECH32 = "BECH32"
  val DATE = "DATE"
  val WALLET = "WALLET"
  val ENCODING = "ENCODING"

  val COMMON_UTILITIES_ID = "COMMON_UTILITIES_ID"

  val SCHEMA_ID = "SCHEMA_ID"
  val SCHEMA_OWNABLE_ID = "SCHEMA_OWNABLE_ID"
  val SCHEMA_DATA = "SCHEMA_DATA"
  val SCHEMA_DOCUMENT ="SCHEMA_DOCUMENT"
  val SCHEMA_PROPERTY ="SCHEMA_PROPERTY"

}
