package constants

object Module {

  val UTILITIES_MICRO_NUMBER = "UTILITIES_MICRO_NUMBER"
  val UTILITIES_ATTO_NUMBER = "UTILITIES_ATTO_NUMBER"
  val UTILITIES_BECH32 = "UTILITIES_BECH32"
  val UTILITIES_DATE = "UTILITIES_DATE"
  val UTILITIES_WALLET = "UTILITIES_WALLET"
  val UTILITIES_SECRETS = "UTILITIES_SECRETS"

}
