// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/define/service.v1.proto

package identities.transactions.define;

public final class ServiceV1 {
  private ServiceV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@modules/identities/internal/transactio" +
      "ns/define/service.v1.proto\022\036identities.t" +
      "ransactions.define\032\034google/api/annotatio" +
      "ns.proto\032@modules/identities/internal/tr" +
      "ansactions/define/message.v1.proto\032Amodu" +
      "les/identities/internal/transactions/def" +
      "ine/response.v1.proto2\211\001\n\007Service\022~\n\006Han" +
      "dle\022\'.identities.transactions.define.Mes" +
      "sage\032(.identities.transactions.define.Re" +
      "sponse\"!\202\323\344\223\002\033\"\031/mantle/identities/defin" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          identities.transactions.define.MessageV1.getDescriptor(),
          identities.transactions.define.ResponseV1.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    identities.transactions.define.MessageV1.getDescriptor();
    identities.transactions.define.ResponseV1.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
