// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/properties/base/mesaProperty.v1.proto

package properties;

public final class MesaPropertyV1 {
  private MesaPropertyV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MesaPropertyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:properties.MesaProperty)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ids.PropertyID id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>.ids.PropertyID id = 1;</code>
     * @return The id.
     */
    ids.PropertyIDV1.PropertyID getId();
    /**
     * <code>.ids.PropertyID id = 1;</code>
     */
    ids.PropertyIDV1.PropertyIDOrBuilder getIdOrBuilder();

    /**
     * <code>.ids.DataID data_i_d = 2;</code>
     * @return Whether the dataID field is set.
     */
    boolean hasDataID();
    /**
     * <code>.ids.DataID data_i_d = 2;</code>
     * @return The dataID.
     */
    ids.DataIDV1.DataID getDataID();
    /**
     * <code>.ids.DataID data_i_d = 2;</code>
     */
    ids.DataIDV1.DataIDOrBuilder getDataIDOrBuilder();
  }
  /**
   * Protobuf type {@code properties.MesaProperty}
   */
  public static final class MesaProperty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:properties.MesaProperty)
      MesaPropertyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MesaProperty.newBuilder() to construct.
    private MesaProperty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MesaProperty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MesaProperty();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return properties.MesaPropertyV1.internal_static_properties_MesaProperty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return properties.MesaPropertyV1.internal_static_properties_MesaProperty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              properties.MesaPropertyV1.MesaProperty.class, properties.MesaPropertyV1.MesaProperty.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private ids.PropertyIDV1.PropertyID id_;
    /**
     * <code>.ids.PropertyID id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.ids.PropertyID id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public ids.PropertyIDV1.PropertyID getId() {
      return id_ == null ? ids.PropertyIDV1.PropertyID.getDefaultInstance() : id_;
    }
    /**
     * <code>.ids.PropertyID id = 1;</code>
     */
    @java.lang.Override
    public ids.PropertyIDV1.PropertyIDOrBuilder getIdOrBuilder() {
      return id_ == null ? ids.PropertyIDV1.PropertyID.getDefaultInstance() : id_;
    }

    public static final int DATA_I_D_FIELD_NUMBER = 2;
    private ids.DataIDV1.DataID dataID_;
    /**
     * <code>.ids.DataID data_i_d = 2;</code>
     * @return Whether the dataID field is set.
     */
    @java.lang.Override
    public boolean hasDataID() {
      return dataID_ != null;
    }
    /**
     * <code>.ids.DataID data_i_d = 2;</code>
     * @return The dataID.
     */
    @java.lang.Override
    public ids.DataIDV1.DataID getDataID() {
      return dataID_ == null ? ids.DataIDV1.DataID.getDefaultInstance() : dataID_;
    }
    /**
     * <code>.ids.DataID data_i_d = 2;</code>
     */
    @java.lang.Override
    public ids.DataIDV1.DataIDOrBuilder getDataIDOrBuilder() {
      return dataID_ == null ? ids.DataIDV1.DataID.getDefaultInstance() : dataID_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != null) {
        output.writeMessage(1, getId());
      }
      if (dataID_ != null) {
        output.writeMessage(2, getDataID());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      if (dataID_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDataID());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof properties.MesaPropertyV1.MesaProperty)) {
        return super.equals(obj);
      }
      properties.MesaPropertyV1.MesaProperty other = (properties.MesaPropertyV1.MesaProperty) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasDataID() != other.hasDataID()) return false;
      if (hasDataID()) {
        if (!getDataID()
            .equals(other.getDataID())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasDataID()) {
        hash = (37 * hash) + DATA_I_D_FIELD_NUMBER;
        hash = (53 * hash) + getDataID().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static properties.MesaPropertyV1.MesaProperty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static properties.MesaPropertyV1.MesaProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static properties.MesaPropertyV1.MesaProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static properties.MesaPropertyV1.MesaProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(properties.MesaPropertyV1.MesaProperty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code properties.MesaProperty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:properties.MesaProperty)
        properties.MesaPropertyV1.MesaPropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return properties.MesaPropertyV1.internal_static_properties_MesaProperty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return properties.MesaPropertyV1.internal_static_properties_MesaProperty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                properties.MesaPropertyV1.MesaProperty.class, properties.MesaPropertyV1.MesaProperty.Builder.class);
      }

      // Construct using properties.MesaPropertyV1.MesaProperty.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = null;
        if (idBuilder_ != null) {
          idBuilder_.dispose();
          idBuilder_ = null;
        }
        dataID_ = null;
        if (dataIDBuilder_ != null) {
          dataIDBuilder_.dispose();
          dataIDBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return properties.MesaPropertyV1.internal_static_properties_MesaProperty_descriptor;
      }

      @java.lang.Override
      public properties.MesaPropertyV1.MesaProperty getDefaultInstanceForType() {
        return properties.MesaPropertyV1.MesaProperty.getDefaultInstance();
      }

      @java.lang.Override
      public properties.MesaPropertyV1.MesaProperty build() {
        properties.MesaPropertyV1.MesaProperty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public properties.MesaPropertyV1.MesaProperty buildPartial() {
        properties.MesaPropertyV1.MesaProperty result = new properties.MesaPropertyV1.MesaProperty(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(properties.MesaPropertyV1.MesaProperty result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = idBuilder_ == null
              ? id_
              : idBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dataID_ = dataIDBuilder_ == null
              ? dataID_
              : dataIDBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof properties.MesaPropertyV1.MesaProperty) {
          return mergeFrom((properties.MesaPropertyV1.MesaProperty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(properties.MesaPropertyV1.MesaProperty other) {
        if (other == properties.MesaPropertyV1.MesaProperty.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasDataID()) {
          mergeDataID(other.getDataID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getIdFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getDataIDFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private ids.PropertyIDV1.PropertyID id_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ids.PropertyIDV1.PropertyID, ids.PropertyIDV1.PropertyID.Builder, ids.PropertyIDV1.PropertyIDOrBuilder> idBuilder_;
      /**
       * <code>.ids.PropertyID id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.ids.PropertyID id = 1;</code>
       * @return The id.
       */
      public ids.PropertyIDV1.PropertyID getId() {
        if (idBuilder_ == null) {
          return id_ == null ? ids.PropertyIDV1.PropertyID.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>.ids.PropertyID id = 1;</code>
       */
      public Builder setId(ids.PropertyIDV1.PropertyID value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ids.PropertyID id = 1;</code>
       */
      public Builder setId(
          ids.PropertyIDV1.PropertyID.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ids.PropertyID id = 1;</code>
       */
      public Builder mergeId(ids.PropertyIDV1.PropertyID value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            id_ != null &&
            id_ != ids.PropertyIDV1.PropertyID.getDefaultInstance()) {
            getIdBuilder().mergeFrom(value);
          } else {
            id_ = value;
          }
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ids.PropertyID id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = null;
        if (idBuilder_ != null) {
          idBuilder_.dispose();
          idBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ids.PropertyID id = 1;</code>
       */
      public ids.PropertyIDV1.PropertyID.Builder getIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.ids.PropertyID id = 1;</code>
       */
      public ids.PropertyIDV1.PropertyIDOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              ids.PropertyIDV1.PropertyID.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>.ids.PropertyID id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ids.PropertyIDV1.PropertyID, ids.PropertyIDV1.PropertyID.Builder, ids.PropertyIDV1.PropertyIDOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ids.PropertyIDV1.PropertyID, ids.PropertyIDV1.PropertyID.Builder, ids.PropertyIDV1.PropertyIDOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private ids.DataIDV1.DataID dataID_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ids.DataIDV1.DataID, ids.DataIDV1.DataID.Builder, ids.DataIDV1.DataIDOrBuilder> dataIDBuilder_;
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       * @return Whether the dataID field is set.
       */
      public boolean hasDataID() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       * @return The dataID.
       */
      public ids.DataIDV1.DataID getDataID() {
        if (dataIDBuilder_ == null) {
          return dataID_ == null ? ids.DataIDV1.DataID.getDefaultInstance() : dataID_;
        } else {
          return dataIDBuilder_.getMessage();
        }
      }
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       */
      public Builder setDataID(ids.DataIDV1.DataID value) {
        if (dataIDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataID_ = value;
        } else {
          dataIDBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       */
      public Builder setDataID(
          ids.DataIDV1.DataID.Builder builderForValue) {
        if (dataIDBuilder_ == null) {
          dataID_ = builderForValue.build();
        } else {
          dataIDBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       */
      public Builder mergeDataID(ids.DataIDV1.DataID value) {
        if (dataIDBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            dataID_ != null &&
            dataID_ != ids.DataIDV1.DataID.getDefaultInstance()) {
            getDataIDBuilder().mergeFrom(value);
          } else {
            dataID_ = value;
          }
        } else {
          dataIDBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       */
      public Builder clearDataID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataID_ = null;
        if (dataIDBuilder_ != null) {
          dataIDBuilder_.dispose();
          dataIDBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       */
      public ids.DataIDV1.DataID.Builder getDataIDBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDataIDFieldBuilder().getBuilder();
      }
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       */
      public ids.DataIDV1.DataIDOrBuilder getDataIDOrBuilder() {
        if (dataIDBuilder_ != null) {
          return dataIDBuilder_.getMessageOrBuilder();
        } else {
          return dataID_ == null ?
              ids.DataIDV1.DataID.getDefaultInstance() : dataID_;
        }
      }
      /**
       * <code>.ids.DataID data_i_d = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ids.DataIDV1.DataID, ids.DataIDV1.DataID.Builder, ids.DataIDV1.DataIDOrBuilder> 
          getDataIDFieldBuilder() {
        if (dataIDBuilder_ == null) {
          dataIDBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ids.DataIDV1.DataID, ids.DataIDV1.DataID.Builder, ids.DataIDV1.DataIDOrBuilder>(
                  getDataID(),
                  getParentForChildren(),
                  isClean());
          dataID_ = null;
        }
        return dataIDBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:properties.MesaProperty)
    }

    // @@protoc_insertion_point(class_scope:properties.MesaProperty)
    private static final properties.MesaPropertyV1.MesaProperty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new properties.MesaPropertyV1.MesaProperty();
    }

    public static properties.MesaPropertyV1.MesaProperty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MesaProperty>
        PARSER = new com.google.protobuf.AbstractParser<MesaProperty>() {
      @java.lang.Override
      public MesaProperty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MesaProperty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MesaProperty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public properties.MesaPropertyV1.MesaProperty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_properties_MesaProperty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_properties_MesaProperty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,schema/properties/base/mesaProperty.v1" +
      ".proto\022\nproperties\032#schema/ids/base/prop" +
      "ertyID.v1.proto\032\037schema/ids/base/dataID." +
      "v1.proto\032\024gogoproto/gogo.proto\"P\n\014MesaPr" +
      "operty\022\033\n\002id\030\001 \001(\0132\017.ids.PropertyID\022\035\n\010d" +
      "ata_i_d\030\002 \001(\0132\013.ids.DataID:\004\210\240\037\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ids.PropertyIDV1.getDescriptor(),
          ids.DataIDV1.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_properties_MesaProperty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_properties_MesaProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_properties_MesaProperty_descriptor,
        new java.lang.String[] { "Id", "DataID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    ids.PropertyIDV1.getDescriptor();
    ids.DataIDV1.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
