// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/types/types.proto

package com.tendermint.types;

/**
 * <pre>
 * Header defines the structure of a Tendermint block header.
 * </pre>
 *
 * Protobuf type {@code tendermint.types.Header}
 */
public final class Header extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tendermint.types.Header)
    HeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Header.newBuilder() to construct.
  private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Header() {
    chainId_ = "";
    lastCommitHash_ = com.google.protobuf.ByteString.EMPTY;
    dataHash_ = com.google.protobuf.ByteString.EMPTY;
    validatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    nextValidatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    consensusHash_ = com.google.protobuf.ByteString.EMPTY;
    appHash_ = com.google.protobuf.ByteString.EMPTY;
    lastResultsHash_ = com.google.protobuf.ByteString.EMPTY;
    evidenceHash_ = com.google.protobuf.ByteString.EMPTY;
    proposerAddress_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Header();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TypesProto.internal_static_tendermint_types_Header_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TypesProto.internal_static_tendermint_types_Header_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Header.class, Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private com.tendermint.version.Consensus version_;
  /**
   * <pre>
   * basic block info
   * </pre>
   *
   * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
   * @return Whether the version field is set.
   */
  @Override
  public boolean hasVersion() {
    return version_ != null;
  }
  /**
   * <pre>
   * basic block info
   * </pre>
   *
   * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
   * @return The version.
   */
  @Override
  public com.tendermint.version.Consensus getVersion() {
    return version_ == null ? com.tendermint.version.Consensus.getDefaultInstance() : version_;
  }
  /**
   * <pre>
   * basic block info
   * </pre>
   *
   * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
   */
  @Override
  public com.tendermint.version.ConsensusOrBuilder getVersionOrBuilder() {
    return version_ == null ? com.tendermint.version.Consensus.getDefaultInstance() : version_;
  }

  public static final int CHAIN_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object chainId_ = "";
  /**
   * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
   * @return The chainId.
   */
  @Override
  public String getChainId() {
    Object ref = chainId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      chainId_ = s;
      return s;
    }
  }
  /**
   * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
   * @return The bytes for chainId.
   */
  @Override
  public com.google.protobuf.ByteString
      getChainIdBytes() {
    Object ref = chainId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      chainId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEIGHT_FIELD_NUMBER = 3;
  private long height_ = 0L;
  /**
   * <code>int64 height = 3 [json_name = "height"];</code>
   * @return The height.
   */
  @Override
  public long getHeight() {
    return height_;
  }

  public static final int TIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp time_;
  /**
   * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   * @return Whether the time field is set.
   */
  @Override
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   * @return The time.
   */
  @Override
  public com.google.protobuf.Timestamp getTime() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }
  /**
   * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }

  public static final int LAST_BLOCK_ID_FIELD_NUMBER = 5;
  private BlockID lastBlockId_;
  /**
   * <pre>
   * prev block info
   * </pre>
   *
   * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
   * @return Whether the lastBlockId field is set.
   */
  @Override
  public boolean hasLastBlockId() {
    return lastBlockId_ != null;
  }
  /**
   * <pre>
   * prev block info
   * </pre>
   *
   * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
   * @return The lastBlockId.
   */
  @Override
  public BlockID getLastBlockId() {
    return lastBlockId_ == null ? BlockID.getDefaultInstance() : lastBlockId_;
  }
  /**
   * <pre>
   * prev block info
   * </pre>
   *
   * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
   */
  @Override
  public BlockIDOrBuilder getLastBlockIdOrBuilder() {
    return lastBlockId_ == null ? BlockID.getDefaultInstance() : lastBlockId_;
  }

  public static final int LAST_COMMIT_HASH_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString lastCommitHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * hashes of block data
   * </pre>
   *
   * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
   * @return The lastCommitHash.
   */
  @Override
  public com.google.protobuf.ByteString getLastCommitHash() {
    return lastCommitHash_;
  }

  public static final int DATA_HASH_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString dataHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * transactions
   * </pre>
   *
   * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
   * @return The dataHash.
   */
  @Override
  public com.google.protobuf.ByteString getDataHash() {
    return dataHash_;
  }

  public static final int VALIDATORS_HASH_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString validatorsHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * hashes from the app output from the prev block
   * </pre>
   *
   * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
   * @return The validatorsHash.
   */
  @Override
  public com.google.protobuf.ByteString getValidatorsHash() {
    return validatorsHash_;
  }

  public static final int NEXT_VALIDATORS_HASH_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString nextValidatorsHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * validators for the next block
   * </pre>
   *
   * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
   * @return The nextValidatorsHash.
   */
  @Override
  public com.google.protobuf.ByteString getNextValidatorsHash() {
    return nextValidatorsHash_;
  }

  public static final int CONSENSUS_HASH_FIELD_NUMBER = 10;
  private com.google.protobuf.ByteString consensusHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * consensus params for current block
   * </pre>
   *
   * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
   * @return The consensusHash.
   */
  @Override
  public com.google.protobuf.ByteString getConsensusHash() {
    return consensusHash_;
  }

  public static final int APP_HASH_FIELD_NUMBER = 11;
  private com.google.protobuf.ByteString appHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * state after txs from the previous block
   * </pre>
   *
   * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
   * @return The appHash.
   */
  @Override
  public com.google.protobuf.ByteString getAppHash() {
    return appHash_;
  }

  public static final int LAST_RESULTS_HASH_FIELD_NUMBER = 12;
  private com.google.protobuf.ByteString lastResultsHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * root hash of all results from the txs from the previous block
   * </pre>
   *
   * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
   * @return The lastResultsHash.
   */
  @Override
  public com.google.protobuf.ByteString getLastResultsHash() {
    return lastResultsHash_;
  }

  public static final int EVIDENCE_HASH_FIELD_NUMBER = 13;
  private com.google.protobuf.ByteString evidenceHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * consensus info
   * </pre>
   *
   * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
   * @return The evidenceHash.
   */
  @Override
  public com.google.protobuf.ByteString getEvidenceHash() {
    return evidenceHash_;
  }

  public static final int PROPOSER_ADDRESS_FIELD_NUMBER = 14;
  private com.google.protobuf.ByteString proposerAddress_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * original proposer of the block
   * </pre>
   *
   * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
   * @return The proposerAddress.
   */
  @Override
  public com.google.protobuf.ByteString getProposerAddress() {
    return proposerAddress_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != null) {
      output.writeMessage(1, getVersion());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chainId_);
    }
    if (height_ != 0L) {
      output.writeInt64(3, height_);
    }
    if (time_ != null) {
      output.writeMessage(4, getTime());
    }
    if (lastBlockId_ != null) {
      output.writeMessage(5, getLastBlockId());
    }
    if (!lastCommitHash_.isEmpty()) {
      output.writeBytes(6, lastCommitHash_);
    }
    if (!dataHash_.isEmpty()) {
      output.writeBytes(7, dataHash_);
    }
    if (!validatorsHash_.isEmpty()) {
      output.writeBytes(8, validatorsHash_);
    }
    if (!nextValidatorsHash_.isEmpty()) {
      output.writeBytes(9, nextValidatorsHash_);
    }
    if (!consensusHash_.isEmpty()) {
      output.writeBytes(10, consensusHash_);
    }
    if (!appHash_.isEmpty()) {
      output.writeBytes(11, appHash_);
    }
    if (!lastResultsHash_.isEmpty()) {
      output.writeBytes(12, lastResultsHash_);
    }
    if (!evidenceHash_.isEmpty()) {
      output.writeBytes(13, evidenceHash_);
    }
    if (!proposerAddress_.isEmpty()) {
      output.writeBytes(14, proposerAddress_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVersion());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chainId_);
    }
    if (height_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, height_);
    }
    if (time_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTime());
    }
    if (lastBlockId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLastBlockId());
    }
    if (!lastCommitHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, lastCommitHash_);
    }
    if (!dataHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, dataHash_);
    }
    if (!validatorsHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, validatorsHash_);
    }
    if (!nextValidatorsHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, nextValidatorsHash_);
    }
    if (!consensusHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, consensusHash_);
    }
    if (!appHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(11, appHash_);
    }
    if (!lastResultsHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, lastResultsHash_);
    }
    if (!evidenceHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(13, evidenceHash_);
    }
    if (!proposerAddress_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(14, proposerAddress_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Header)) {
      return super.equals(obj);
    }
    Header other = (Header) obj;

    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (!getVersion()
          .equals(other.getVersion())) return false;
    }
    if (!getChainId()
        .equals(other.getChainId())) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (hasTime() != other.hasTime()) return false;
    if (hasTime()) {
      if (!getTime()
          .equals(other.getTime())) return false;
    }
    if (hasLastBlockId() != other.hasLastBlockId()) return false;
    if (hasLastBlockId()) {
      if (!getLastBlockId()
          .equals(other.getLastBlockId())) return false;
    }
    if (!getLastCommitHash()
        .equals(other.getLastCommitHash())) return false;
    if (!getDataHash()
        .equals(other.getDataHash())) return false;
    if (!getValidatorsHash()
        .equals(other.getValidatorsHash())) return false;
    if (!getNextValidatorsHash()
        .equals(other.getNextValidatorsHash())) return false;
    if (!getConsensusHash()
        .equals(other.getConsensusHash())) return false;
    if (!getAppHash()
        .equals(other.getAppHash())) return false;
    if (!getLastResultsHash()
        .equals(other.getLastResultsHash())) return false;
    if (!getEvidenceHash()
        .equals(other.getEvidenceHash())) return false;
    if (!getProposerAddress()
        .equals(other.getProposerAddress())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    hash = (37 * hash) + CHAIN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChainId().hashCode();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeight());
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    if (hasLastBlockId()) {
      hash = (37 * hash) + LAST_BLOCK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLastBlockId().hashCode();
    }
    hash = (37 * hash) + LAST_COMMIT_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getLastCommitHash().hashCode();
    hash = (37 * hash) + DATA_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getDataHash().hashCode();
    hash = (37 * hash) + VALIDATORS_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getValidatorsHash().hashCode();
    hash = (37 * hash) + NEXT_VALIDATORS_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getNextValidatorsHash().hashCode();
    hash = (37 * hash) + CONSENSUS_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getConsensusHash().hashCode();
    hash = (37 * hash) + APP_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getAppHash().hashCode();
    hash = (37 * hash) + LAST_RESULTS_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getLastResultsHash().hashCode();
    hash = (37 * hash) + EVIDENCE_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getEvidenceHash().hashCode();
    hash = (37 * hash) + PROPOSER_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getProposerAddress().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Header parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Header parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Header parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Header parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Header parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Header parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Header parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Header parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Header parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Header parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Header parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Header parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Header prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Header defines the structure of a Tendermint block header.
   * </pre>
   *
   * Protobuf type {@code tendermint.types.Header}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tendermint.types.Header)
      HeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TypesProto.internal_static_tendermint_types_Header_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TypesProto.internal_static_tendermint_types_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Header.class, Builder.class);
    }

    // Construct using com.tendermint.types.Header.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = null;
      if (versionBuilder_ != null) {
        versionBuilder_.dispose();
        versionBuilder_ = null;
      }
      chainId_ = "";
      height_ = 0L;
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      lastBlockId_ = null;
      if (lastBlockIdBuilder_ != null) {
        lastBlockIdBuilder_.dispose();
        lastBlockIdBuilder_ = null;
      }
      lastCommitHash_ = com.google.protobuf.ByteString.EMPTY;
      dataHash_ = com.google.protobuf.ByteString.EMPTY;
      validatorsHash_ = com.google.protobuf.ByteString.EMPTY;
      nextValidatorsHash_ = com.google.protobuf.ByteString.EMPTY;
      consensusHash_ = com.google.protobuf.ByteString.EMPTY;
      appHash_ = com.google.protobuf.ByteString.EMPTY;
      lastResultsHash_ = com.google.protobuf.ByteString.EMPTY;
      evidenceHash_ = com.google.protobuf.ByteString.EMPTY;
      proposerAddress_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TypesProto.internal_static_tendermint_types_Header_descriptor;
    }

    @Override
    public Header getDefaultInstanceForType() {
      return Header.getDefaultInstance();
    }

    @Override
    public Header build() {
      Header result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Header buildPartial() {
      Header result = new Header(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Header result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = versionBuilder_ == null
            ? version_
            : versionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.chainId_ = chainId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.height_ = height_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.time_ = timeBuilder_ == null
            ? time_
            : timeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lastBlockId_ = lastBlockIdBuilder_ == null
            ? lastBlockId_
            : lastBlockIdBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lastCommitHash_ = lastCommitHash_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.dataHash_ = dataHash_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.validatorsHash_ = validatorsHash_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.nextValidatorsHash_ = nextValidatorsHash_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.consensusHash_ = consensusHash_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.appHash_ = appHash_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.lastResultsHash_ = lastResultsHash_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.evidenceHash_ = evidenceHash_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.proposerAddress_ = proposerAddress_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Header) {
        return mergeFrom((Header)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Header other) {
      if (other == Header.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        mergeVersion(other.getVersion());
      }
      if (!other.getChainId().isEmpty()) {
        chainId_ = other.chainId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getHeight() != 0L) {
        setHeight(other.getHeight());
      }
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      if (other.hasLastBlockId()) {
        mergeLastBlockId(other.getLastBlockId());
      }
      if (other.getLastCommitHash() != com.google.protobuf.ByteString.EMPTY) {
        setLastCommitHash(other.getLastCommitHash());
      }
      if (other.getDataHash() != com.google.protobuf.ByteString.EMPTY) {
        setDataHash(other.getDataHash());
      }
      if (other.getValidatorsHash() != com.google.protobuf.ByteString.EMPTY) {
        setValidatorsHash(other.getValidatorsHash());
      }
      if (other.getNextValidatorsHash() != com.google.protobuf.ByteString.EMPTY) {
        setNextValidatorsHash(other.getNextValidatorsHash());
      }
      if (other.getConsensusHash() != com.google.protobuf.ByteString.EMPTY) {
        setConsensusHash(other.getConsensusHash());
      }
      if (other.getAppHash() != com.google.protobuf.ByteString.EMPTY) {
        setAppHash(other.getAppHash());
      }
      if (other.getLastResultsHash() != com.google.protobuf.ByteString.EMPTY) {
        setLastResultsHash(other.getLastResultsHash());
      }
      if (other.getEvidenceHash() != com.google.protobuf.ByteString.EMPTY) {
        setEvidenceHash(other.getEvidenceHash());
      }
      if (other.getProposerAddress() != com.google.protobuf.ByteString.EMPTY) {
        setProposerAddress(other.getProposerAddress());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getVersionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              chainId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              height_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getLastBlockIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              lastCommitHash_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              dataHash_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              validatorsHash_ = input.readBytes();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              nextValidatorsHash_ = input.readBytes();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              consensusHash_ = input.readBytes();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              appHash_ = input.readBytes();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              lastResultsHash_ = input.readBytes();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              evidenceHash_ = input.readBytes();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              proposerAddress_ = input.readBytes();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.tendermint.version.Consensus version_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.version.Consensus, com.tendermint.version.Consensus.Builder, com.tendermint.version.ConsensusOrBuilder> versionBuilder_;
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     * @return Whether the version field is set.
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     * @return The version.
     */
    public com.tendermint.version.Consensus getVersion() {
      if (versionBuilder_ == null) {
        return version_ == null ? com.tendermint.version.Consensus.getDefaultInstance() : version_;
      } else {
        return versionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public Builder setVersion(com.tendermint.version.Consensus value) {
      if (versionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;
      } else {
        versionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public Builder setVersion(
        com.tendermint.version.Consensus.Builder builderForValue) {
      if (versionBuilder_ == null) {
        version_ = builderForValue.build();
      } else {
        versionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public Builder mergeVersion(com.tendermint.version.Consensus value) {
      if (versionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          version_ != null &&
          version_ != com.tendermint.version.Consensus.getDefaultInstance()) {
          getVersionBuilder().mergeFrom(value);
        } else {
          version_ = value;
        }
      } else {
        versionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = null;
      if (versionBuilder_ != null) {
        versionBuilder_.dispose();
        versionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public com.tendermint.version.Consensus.Builder getVersionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getVersionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public com.tendermint.version.ConsensusOrBuilder getVersionOrBuilder() {
      if (versionBuilder_ != null) {
        return versionBuilder_.getMessageOrBuilder();
      } else {
        return version_ == null ?
            com.tendermint.version.Consensus.getDefaultInstance() : version_;
      }
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.version.Consensus, com.tendermint.version.Consensus.Builder, com.tendermint.version.ConsensusOrBuilder> 
        getVersionFieldBuilder() {
      if (versionBuilder_ == null) {
        versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tendermint.version.Consensus, com.tendermint.version.Consensus.Builder, com.tendermint.version.ConsensusOrBuilder>(
                getVersion(),
                getParentForChildren(),
                isClean());
        version_ = null;
      }
      return versionBuilder_;
    }

    private Object chainId_ = "";
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @return The chainId.
     */
    public String getChainId() {
      Object ref = chainId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        chainId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @return The bytes for chainId.
     */
    public com.google.protobuf.ByteString
        getChainIdBytes() {
      Object ref = chainId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        chainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @param value The chainId to set.
     * @return This builder for chaining.
     */
    public Builder setChainId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      chainId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChainId() {
      chainId_ = getDefaultInstance().getChainId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @param value The bytes for chainId to set.
     * @return This builder for chaining.
     */
    public Builder setChainIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      chainId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long height_ ;
    /**
     * <code>int64 height = 3 [json_name = "height"];</code>
     * @return The height.
     */
    @Override
    public long getHeight() {
      return height_;
    }
    /**
     * <code>int64 height = 3 [json_name = "height"];</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {

      height_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 height = 3 [json_name = "height"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000004);
      height_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp time_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return Whether the time field is set.
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return The time.
     */
    public com.google.protobuf.Timestamp getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public Builder setTime(com.google.protobuf.Timestamp value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
      } else {
        timeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public Builder setTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public Builder mergeTime(com.google.protobuf.Timestamp value) {
      if (timeBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          time_ != null &&
          time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimeBuilder().mergeFrom(value);
        } else {
          time_ = value;
        }
      } else {
        timeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : time_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }

    private BlockID lastBlockId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BlockID, BlockID.Builder, BlockIDOrBuilder> lastBlockIdBuilder_;
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     * @return Whether the lastBlockId field is set.
     */
    public boolean hasLastBlockId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     * @return The lastBlockId.
     */
    public BlockID getLastBlockId() {
      if (lastBlockIdBuilder_ == null) {
        return lastBlockId_ == null ? BlockID.getDefaultInstance() : lastBlockId_;
      } else {
        return lastBlockIdBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public Builder setLastBlockId(BlockID value) {
      if (lastBlockIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastBlockId_ = value;
      } else {
        lastBlockIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public Builder setLastBlockId(
        BlockID.Builder builderForValue) {
      if (lastBlockIdBuilder_ == null) {
        lastBlockId_ = builderForValue.build();
      } else {
        lastBlockIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public Builder mergeLastBlockId(BlockID value) {
      if (lastBlockIdBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          lastBlockId_ != null &&
          lastBlockId_ != BlockID.getDefaultInstance()) {
          getLastBlockIdBuilder().mergeFrom(value);
        } else {
          lastBlockId_ = value;
        }
      } else {
        lastBlockIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public Builder clearLastBlockId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      lastBlockId_ = null;
      if (lastBlockIdBuilder_ != null) {
        lastBlockIdBuilder_.dispose();
        lastBlockIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public BlockID.Builder getLastBlockIdBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getLastBlockIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public BlockIDOrBuilder getLastBlockIdOrBuilder() {
      if (lastBlockIdBuilder_ != null) {
        return lastBlockIdBuilder_.getMessageOrBuilder();
      } else {
        return lastBlockId_ == null ?
            BlockID.getDefaultInstance() : lastBlockId_;
      }
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BlockID, BlockID.Builder, BlockIDOrBuilder>
        getLastBlockIdFieldBuilder() {
      if (lastBlockIdBuilder_ == null) {
        lastBlockIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BlockID, BlockID.Builder, BlockIDOrBuilder>(
                getLastBlockId(),
                getParentForChildren(),
                isClean());
        lastBlockId_ = null;
      }
      return lastBlockIdBuilder_;
    }

    private com.google.protobuf.ByteString lastCommitHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * hashes of block data
     * </pre>
     *
     * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
     * @return The lastCommitHash.
     */
    @Override
    public com.google.protobuf.ByteString getLastCommitHash() {
      return lastCommitHash_;
    }
    /**
     * <pre>
     * hashes of block data
     * </pre>
     *
     * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
     * @param value The lastCommitHash to set.
     * @return This builder for chaining.
     */
    public Builder setLastCommitHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      lastCommitHash_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * hashes of block data
     * </pre>
     *
     * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCommitHash() {
      bitField0_ = (bitField0_ & ~0x00000020);
      lastCommitHash_ = getDefaultInstance().getLastCommitHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString dataHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * transactions
     * </pre>
     *
     * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
     * @return The dataHash.
     */
    @Override
    public com.google.protobuf.ByteString getDataHash() {
      return dataHash_;
    }
    /**
     * <pre>
     * transactions
     * </pre>
     *
     * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
     * @param value The dataHash to set.
     * @return This builder for chaining.
     */
    public Builder setDataHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      dataHash_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * transactions
     * </pre>
     *
     * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDataHash() {
      bitField0_ = (bitField0_ & ~0x00000040);
      dataHash_ = getDefaultInstance().getDataHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString validatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * hashes from the app output from the prev block
     * </pre>
     *
     * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
     * @return The validatorsHash.
     */
    @Override
    public com.google.protobuf.ByteString getValidatorsHash() {
      return validatorsHash_;
    }
    /**
     * <pre>
     * hashes from the app output from the prev block
     * </pre>
     *
     * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
     * @param value The validatorsHash to set.
     * @return This builder for chaining.
     */
    public Builder setValidatorsHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      validatorsHash_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * hashes from the app output from the prev block
     * </pre>
     *
     * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValidatorsHash() {
      bitField0_ = (bitField0_ & ~0x00000080);
      validatorsHash_ = getDefaultInstance().getValidatorsHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString nextValidatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * validators for the next block
     * </pre>
     *
     * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
     * @return The nextValidatorsHash.
     */
    @Override
    public com.google.protobuf.ByteString getNextValidatorsHash() {
      return nextValidatorsHash_;
    }
    /**
     * <pre>
     * validators for the next block
     * </pre>
     *
     * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
     * @param value The nextValidatorsHash to set.
     * @return This builder for chaining.
     */
    public Builder setNextValidatorsHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      nextValidatorsHash_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * validators for the next block
     * </pre>
     *
     * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNextValidatorsHash() {
      bitField0_ = (bitField0_ & ~0x00000100);
      nextValidatorsHash_ = getDefaultInstance().getNextValidatorsHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString consensusHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * consensus params for current block
     * </pre>
     *
     * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
     * @return The consensusHash.
     */
    @Override
    public com.google.protobuf.ByteString getConsensusHash() {
      return consensusHash_;
    }
    /**
     * <pre>
     * consensus params for current block
     * </pre>
     *
     * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
     * @param value The consensusHash to set.
     * @return This builder for chaining.
     */
    public Builder setConsensusHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      consensusHash_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * consensus params for current block
     * </pre>
     *
     * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearConsensusHash() {
      bitField0_ = (bitField0_ & ~0x00000200);
      consensusHash_ = getDefaultInstance().getConsensusHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString appHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * state after txs from the previous block
     * </pre>
     *
     * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
     * @return The appHash.
     */
    @Override
    public com.google.protobuf.ByteString getAppHash() {
      return appHash_;
    }
    /**
     * <pre>
     * state after txs from the previous block
     * </pre>
     *
     * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
     * @param value The appHash to set.
     * @return This builder for chaining.
     */
    public Builder setAppHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      appHash_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * state after txs from the previous block
     * </pre>
     *
     * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAppHash() {
      bitField0_ = (bitField0_ & ~0x00000400);
      appHash_ = getDefaultInstance().getAppHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString lastResultsHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * root hash of all results from the txs from the previous block
     * </pre>
     *
     * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
     * @return The lastResultsHash.
     */
    @Override
    public com.google.protobuf.ByteString getLastResultsHash() {
      return lastResultsHash_;
    }
    /**
     * <pre>
     * root hash of all results from the txs from the previous block
     * </pre>
     *
     * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
     * @param value The lastResultsHash to set.
     * @return This builder for chaining.
     */
    public Builder setLastResultsHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      lastResultsHash_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * root hash of all results from the txs from the previous block
     * </pre>
     *
     * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLastResultsHash() {
      bitField0_ = (bitField0_ & ~0x00000800);
      lastResultsHash_ = getDefaultInstance().getLastResultsHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString evidenceHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * consensus info
     * </pre>
     *
     * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
     * @return The evidenceHash.
     */
    @Override
    public com.google.protobuf.ByteString getEvidenceHash() {
      return evidenceHash_;
    }
    /**
     * <pre>
     * consensus info
     * </pre>
     *
     * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
     * @param value The evidenceHash to set.
     * @return This builder for chaining.
     */
    public Builder setEvidenceHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      evidenceHash_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * consensus info
     * </pre>
     *
     * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEvidenceHash() {
      bitField0_ = (bitField0_ & ~0x00001000);
      evidenceHash_ = getDefaultInstance().getEvidenceHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString proposerAddress_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * original proposer of the block
     * </pre>
     *
     * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
     * @return The proposerAddress.
     */
    @Override
    public com.google.protobuf.ByteString getProposerAddress() {
      return proposerAddress_;
    }
    /**
     * <pre>
     * original proposer of the block
     * </pre>
     *
     * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
     * @param value The proposerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setProposerAddress(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      proposerAddress_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * original proposer of the block
     * </pre>
     *
     * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProposerAddress() {
      bitField0_ = (bitField0_ & ~0x00002000);
      proposerAddress_ = getDefaultInstance().getProposerAddress();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tendermint.types.Header)
  }

  // @@protoc_insertion_point(class_scope:tendermint.types.Header)
  private static final Header DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Header();
  }

  public static Header getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Header>
      PARSER = new com.google.protobuf.AbstractParser<Header>() {
    @Override
    public Header parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Header> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Header> getParserForType() {
    return PARSER;
  }

  @Override
  public Header getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

