// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/tx/v1beta1/service.proto

package com.cosmos.tx.v1beta1;

/**
 * <pre>
 * GetTxsEventRequest is the request type for the Service.TxsByEvents
 * RPC method.
 * </pre>
 *
 * Protobuf type {@code cosmos.tx.v1beta1.GetTxsEventRequest}
 */
public final class GetTxsEventRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cosmos.tx.v1beta1.GetTxsEventRequest)
    GetTxsEventRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTxsEventRequest.newBuilder() to construct.
  private GetTxsEventRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTxsEventRequest() {
    events_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    orderBy_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTxsEventRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ServiceProto.internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ServiceProto.internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetTxsEventRequest.class, Builder.class);
  }

  public static final int EVENTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList events_;
  /**
   * <pre>
   * events is the list of transaction event type.
   * </pre>
   *
   * <code>repeated string events = 1 [json_name = "events"];</code>
   * @return A list containing the events.
   */
  public com.google.protobuf.ProtocolStringList
      getEventsList() {
    return events_;
  }
  /**
   * <pre>
   * events is the list of transaction event type.
   * </pre>
   *
   * <code>repeated string events = 1 [json_name = "events"];</code>
   * @return The count of events.
   */
  public int getEventsCount() {
    return events_.size();
  }
  /**
   * <pre>
   * events is the list of transaction event type.
   * </pre>
   *
   * <code>repeated string events = 1 [json_name = "events"];</code>
   * @param index The index of the element to return.
   * @return The events at the given index.
   */
  public String getEvents(int index) {
    return events_.get(index);
  }
  /**
   * <pre>
   * events is the list of transaction event type.
   * </pre>
   *
   * <code>repeated string events = 1 [json_name = "events"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the events at the given index.
   */
  public com.google.protobuf.ByteString
      getEventsBytes(int index) {
    return events_.getByteString(index);
  }

  public static final int PAGINATION_FIELD_NUMBER = 2;
  private com.cosmos.base.query.v1beta1.PageRequest pagination_;
  /**
   * <pre>
   * pagination defines a pagination for the request.
   * </pre>
   *
   * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  @Override
  public boolean hasPagination() {
    return pagination_ != null;
  }
  /**
   * <pre>
   * pagination defines a pagination for the request.
   * </pre>
   *
   * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  @Override
  public com.cosmos.base.query.v1beta1.PageRequest getPagination() {
    return pagination_ == null ? com.cosmos.base.query.v1beta1.PageRequest.getDefaultInstance() : pagination_;
  }
  /**
   * <pre>
   * pagination defines a pagination for the request.
   * </pre>
   *
   * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
   */
  @Override
  public com.cosmos.base.query.v1beta1.PageRequestOrBuilder getPaginationOrBuilder() {
    return pagination_ == null ? com.cosmos.base.query.v1beta1.PageRequest.getDefaultInstance() : pagination_;
  }

  public static final int ORDER_BY_FIELD_NUMBER = 3;
  private int orderBy_ = 0;
  /**
   * <code>.cosmos.tx.v1beta1.OrderBy order_by = 3 [json_name = "orderBy"];</code>
   * @return The enum numeric value on the wire for orderBy.
   */
  @Override public int getOrderByValue() {
    return orderBy_;
  }
  /**
   * <code>.cosmos.tx.v1beta1.OrderBy order_by = 3 [json_name = "orderBy"];</code>
   * @return The orderBy.
   */
  @Override public OrderBy getOrderBy() {
    OrderBy result = OrderBy.forNumber(orderBy_);
    return result == null ? OrderBy.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < events_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, events_.getRaw(i));
    }
    if (pagination_ != null) {
      output.writeMessage(2, getPagination());
    }
    if (orderBy_ != OrderBy.ORDER_BY_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, orderBy_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < events_.size(); i++) {
        dataSize += computeStringSizeNoTag(events_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEventsList().size();
    }
    if (pagination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPagination());
    }
    if (orderBy_ != OrderBy.ORDER_BY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, orderBy_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetTxsEventRequest)) {
      return super.equals(obj);
    }
    GetTxsEventRequest other = (GetTxsEventRequest) obj;

    if (!getEventsList()
        .equals(other.getEventsList())) return false;
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (orderBy_ != other.orderBy_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEventsCount() > 0) {
      hash = (37 * hash) + EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getEventsList().hashCode();
    }
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    hash = (37 * hash) + ORDER_BY_FIELD_NUMBER;
    hash = (53 * hash) + orderBy_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetTxsEventRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetTxsEventRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetTxsEventRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetTxsEventRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetTxsEventRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetTxsEventRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetTxsEventRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetTxsEventRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetTxsEventRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetTxsEventRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetTxsEventRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetTxsEventRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetTxsEventRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * GetTxsEventRequest is the request type for the Service.TxsByEvents
   * RPC method.
   * </pre>
   *
   * Protobuf type {@code cosmos.tx.v1beta1.GetTxsEventRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cosmos.tx.v1beta1.GetTxsEventRequest)
      GetTxsEventRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServiceProto.internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServiceProto.internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetTxsEventRequest.class, Builder.class);
    }

    // Construct using com.cosmos.tx.v1beta1.GetTxsEventRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      events_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      orderBy_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ServiceProto.internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_descriptor;
    }

    @Override
    public GetTxsEventRequest getDefaultInstanceForType() {
      return GetTxsEventRequest.getDefaultInstance();
    }

    @Override
    public GetTxsEventRequest build() {
      GetTxsEventRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetTxsEventRequest buildPartial() {
      GetTxsEventRequest result = new GetTxsEventRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(GetTxsEventRequest result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        events_ = events_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.events_ = events_;
    }

    private void buildPartial0(GetTxsEventRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pagination_ = paginationBuilder_ == null
            ? pagination_
            : paginationBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.orderBy_ = orderBy_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetTxsEventRequest) {
        return mergeFrom((GetTxsEventRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetTxsEventRequest other) {
      if (other == GetTxsEventRequest.getDefaultInstance()) return this;
      if (!other.events_.isEmpty()) {
        if (events_.isEmpty()) {
          events_ = other.events_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureEventsIsMutable();
          events_.addAll(other.events_);
        }
        onChanged();
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      if (other.orderBy_ != 0) {
        setOrderByValue(other.getOrderByValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              ensureEventsIsMutable();
              events_.add(s);
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPaginationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              orderBy_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList events_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEventsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        events_ = new com.google.protobuf.LazyStringArrayList(events_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @return A list containing the events.
     */
    public com.google.protobuf.ProtocolStringList
        getEventsList() {
      return events_.getUnmodifiableView();
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @return The count of events.
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @param index The index of the element to return.
     * @return The events at the given index.
     */
    public String getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the events at the given index.
     */
    public com.google.protobuf.ByteString
        getEventsBytes(int index) {
      return events_.getByteString(index);
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @param index The index to set the value at.
     * @param value The events to set.
     * @return This builder for chaining.
     */
    public Builder setEvents(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEventsIsMutable();
      events_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @param value The events to add.
     * @return This builder for chaining.
     */
    public Builder addEvents(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEventsIsMutable();
      events_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @param values The events to add.
     * @return This builder for chaining.
     */
    public Builder addAllEvents(
        Iterable<String> values) {
      ensureEventsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, events_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEvents() {
      events_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * events is the list of transaction event type.
     * </pre>
     *
     * <code>repeated string events = 1 [json_name = "events"];</code>
     * @param value The bytes of the events to add.
     * @return This builder for chaining.
     */
    public Builder addEventsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureEventsIsMutable();
      events_.add(value);
      onChanged();
      return this;
    }

    private com.cosmos.base.query.v1beta1.PageRequest pagination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cosmos.base.query.v1beta1.PageRequest, com.cosmos.base.query.v1beta1.PageRequest.Builder, com.cosmos.base.query.v1beta1.PageRequestOrBuilder> paginationBuilder_;
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     * @return The pagination.
     */
    public com.cosmos.base.query.v1beta1.PageRequest getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? com.cosmos.base.query.v1beta1.PageRequest.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     */
    public Builder setPagination(com.cosmos.base.query.v1beta1.PageRequest value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
      } else {
        paginationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     */
    public Builder setPagination(
        com.cosmos.base.query.v1beta1.PageRequest.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     */
    public Builder mergePagination(com.cosmos.base.query.v1beta1.PageRequest value) {
      if (paginationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          pagination_ != null &&
          pagination_ != com.cosmos.base.query.v1beta1.PageRequest.getDefaultInstance()) {
          getPaginationBuilder().mergeFrom(value);
        } else {
          pagination_ = value;
        }
      } else {
        paginationBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     */
    public Builder clearPagination() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     */
    public com.cosmos.base.query.v1beta1.PageRequest.Builder getPaginationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPaginationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     */
    public com.cosmos.base.query.v1beta1.PageRequestOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            com.cosmos.base.query.v1beta1.PageRequest.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <pre>
     * pagination defines a pagination for the request.
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cosmos.base.query.v1beta1.PageRequest, com.cosmos.base.query.v1beta1.PageRequest.Builder, com.cosmos.base.query.v1beta1.PageRequestOrBuilder> 
        getPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cosmos.base.query.v1beta1.PageRequest, com.cosmos.base.query.v1beta1.PageRequest.Builder, com.cosmos.base.query.v1beta1.PageRequestOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }

    private int orderBy_ = 0;
    /**
     * <code>.cosmos.tx.v1beta1.OrderBy order_by = 3 [json_name = "orderBy"];</code>
     * @return The enum numeric value on the wire for orderBy.
     */
    @Override public int getOrderByValue() {
      return orderBy_;
    }
    /**
     * <code>.cosmos.tx.v1beta1.OrderBy order_by = 3 [json_name = "orderBy"];</code>
     * @param value The enum numeric value on the wire for orderBy to set.
     * @return This builder for chaining.
     */
    public Builder setOrderByValue(int value) {
      orderBy_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.cosmos.tx.v1beta1.OrderBy order_by = 3 [json_name = "orderBy"];</code>
     * @return The orderBy.
     */
    @Override
    public OrderBy getOrderBy() {
      OrderBy result = OrderBy.forNumber(orderBy_);
      return result == null ? OrderBy.UNRECOGNIZED : result;
    }
    /**
     * <code>.cosmos.tx.v1beta1.OrderBy order_by = 3 [json_name = "orderBy"];</code>
     * @param value The orderBy to set.
     * @return This builder for chaining.
     */
    public Builder setOrderBy(OrderBy value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      orderBy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.cosmos.tx.v1beta1.OrderBy order_by = 3 [json_name = "orderBy"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderBy() {
      bitField0_ = (bitField0_ & ~0x00000004);
      orderBy_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cosmos.tx.v1beta1.GetTxsEventRequest)
  }

  // @@protoc_insertion_point(class_scope:cosmos.tx.v1beta1.GetTxsEventRequest)
  private static final GetTxsEventRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetTxsEventRequest();
  }

  public static GetTxsEventRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTxsEventRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetTxsEventRequest>() {
    @Override
    public GetTxsEventRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetTxsEventRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetTxsEventRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public GetTxsEventRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

