// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/crypto/multisig/v1beta1/multisig.proto

package com.cosmos.crypto.multisig.v1beta1;

/**
 * <pre>
 * MultiSignature wraps the signatures from a multisig.LegacyAminoPubKey.
 * See cosmos.tx.v1betata1.ModeInfo.Multi for how to specify which signers
 * signed and with which modes.
 * </pre>
 *
 * Protobuf type {@code cosmos.crypto.multisig.v1beta1.MultiSignature}
 */
public final class MultiSignature extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cosmos.crypto.multisig.v1beta1.MultiSignature)
    MultiSignatureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MultiSignature.newBuilder() to construct.
  private MultiSignature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MultiSignature() {
    signatures_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new MultiSignature();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MultisigProto.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MultisigProto.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MultiSignature.class, Builder.class);
  }

  public static final int SIGNATURES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.ByteString> signatures_;
  /**
   * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
   * @return A list containing the signatures.
   */
  @Override
  public java.util.List<com.google.protobuf.ByteString>
      getSignaturesList() {
    return signatures_;
  }
  /**
   * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
   * @return The count of signatures.
   */
  public int getSignaturesCount() {
    return signatures_.size();
  }
  /**
   * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
   * @param index The index of the element to return.
   * @return The signatures at the given index.
   */
  public com.google.protobuf.ByteString getSignatures(int index) {
    return signatures_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < signatures_.size(); i++) {
      output.writeBytes(1, signatures_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < signatures_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(signatures_.get(i));
      }
      size += dataSize;
      size += 1 * getSignaturesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MultiSignature)) {
      return super.equals(obj);
    }
    MultiSignature other = (MultiSignature) obj;

    if (!getSignaturesList()
        .equals(other.getSignaturesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSignaturesCount() > 0) {
      hash = (37 * hash) + SIGNATURES_FIELD_NUMBER;
      hash = (53 * hash) + getSignaturesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MultiSignature parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MultiSignature parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MultiSignature parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MultiSignature parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MultiSignature parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MultiSignature parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MultiSignature parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MultiSignature parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MultiSignature parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MultiSignature parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MultiSignature parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MultiSignature parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MultiSignature prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MultiSignature wraps the signatures from a multisig.LegacyAminoPubKey.
   * See cosmos.tx.v1betata1.ModeInfo.Multi for how to specify which signers
   * signed and with which modes.
   * </pre>
   *
   * Protobuf type {@code cosmos.crypto.multisig.v1beta1.MultiSignature}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cosmos.crypto.multisig.v1beta1.MultiSignature)
      MultiSignatureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MultisigProto.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MultisigProto.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MultiSignature.class, Builder.class);
    }

    // Construct using com.cosmos.crypto.multisig.v1beta1.MultiSignature.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      signatures_ = java.util.Collections.emptyList();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MultisigProto.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor;
    }

    @Override
    public MultiSignature getDefaultInstanceForType() {
      return MultiSignature.getDefaultInstance();
    }

    @Override
    public MultiSignature build() {
      MultiSignature result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MultiSignature buildPartial() {
      MultiSignature result = new MultiSignature(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(MultiSignature result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        signatures_ = java.util.Collections.unmodifiableList(signatures_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.signatures_ = signatures_;
    }

    private void buildPartial0(MultiSignature result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MultiSignature) {
        return mergeFrom((MultiSignature)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MultiSignature other) {
      if (other == MultiSignature.getDefaultInstance()) return this;
      if (!other.signatures_.isEmpty()) {
        if (signatures_.isEmpty()) {
          signatures_ = other.signatures_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSignaturesIsMutable();
          signatures_.addAll(other.signatures_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureSignaturesIsMutable();
              signatures_.add(v);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.protobuf.ByteString> signatures_ = java.util.Collections.emptyList();
    private void ensureSignaturesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        signatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>(signatures_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
     * @return A list containing the signatures.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getSignaturesList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(signatures_) : signatures_;
    }
    /**
     * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
     * @return The count of signatures.
     */
    public int getSignaturesCount() {
      return signatures_.size();
    }
    /**
     * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
     * @param index The index of the element to return.
     * @return The signatures at the given index.
     */
    public com.google.protobuf.ByteString getSignatures(int index) {
      return signatures_.get(index);
    }
    /**
     * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
     * @param index The index to set the value at.
     * @param value The signatures to set.
     * @return This builder for chaining.
     */
    public Builder setSignatures(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSignaturesIsMutable();
      signatures_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
     * @param value The signatures to add.
     * @return This builder for chaining.
     */
    public Builder addSignatures(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSignaturesIsMutable();
      signatures_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
     * @param values The signatures to add.
     * @return This builder for chaining.
     */
    public Builder addAllSignatures(
        Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureSignaturesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, signatures_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes signatures = 1 [json_name = "signatures"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSignatures() {
      signatures_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cosmos.crypto.multisig.v1beta1.MultiSignature)
  }

  // @@protoc_insertion_point(class_scope:cosmos.crypto.multisig.v1beta1.MultiSignature)
  private static final MultiSignature DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MultiSignature();
  }

  public static MultiSignature getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MultiSignature>
      PARSER = new com.google.protobuf.AbstractParser<MultiSignature>() {
    @Override
    public MultiSignature parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MultiSignature> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MultiSignature> getParserForType() {
    return PARSER;
  }

  @Override
  public MultiSignature getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

